name : Deploy Application Docker Image to EC2 instance

on:
  push:
    branches: [main]

jobs:
  Continous-Integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
      - uses: aws